### PR TITLE
Storybook

### PR DESCRIPTION
**Pull request by SilviaBarcellini**
-`npx sb init` (https://storybook.js.org/docs/react/get-started/install)
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in `.storybook/main.js` (careful with import/export)
- Load example component in `pages/index.tsx`
- Ignore `/storybook-static`(first build, then ignore)
- Add `.eslintignore`
- `npm run storybook`to run storybook (view single component)
- `npm run dev` to run next.js (full view)

- Support CSS Modules in Storybook
(https://github.com/negan1911/storybook-css-modules-preset)

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by mrana17 — APPROVED** [review]
gj 🚀

**Review by oersoy91 — APPROVED** [review]

**Comment by oersoy91** [comment]
GJ 🚀

**Review by m-wiemers — APPROVED** [review]
I like deep pink 🎀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Pull request merged**
